# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- checkout: self
  submodules: true
- script: |
     sudo apt install -y dos2unix libboost-all-dev texinfo texi2html gdb curl cpanminus
     cpanm --local-lib=~/perl5 local::lib App::Prove Modern::Perl Capture::Tiny Capture::Tiny::Extended Path::Tiny File::Path Template Template::Plugin::YAML Test::Differences Text::Table CPU::Z80::Assembler Test::Cmd::Common Test::HexDifferences Data::HexDump Object::Tiny::RW Regexp::Common List::Uniq Clone
     eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
   displayName: "Install prerequisites"
- script: |
    ./build.sh -e -t
  displayName: 'build.sh'
