name: z88dk
base: core18
version: '0.1'
summary: Development kit for Z80 machiens
description: |
  C compiler, assembler and libraries for over 100 z80 family machines.
  

grade: devel 
confinement: strict


parts:
  part-z88dk:
    plugin: make
    source-type: git
    source: https://github.com/z88dk/z88dk.git
    # See 'snapcraft plugins'
    build-environment:
      - BUILD_SDCC: "1"
    override-build: |
      ./build.sh -i $SNAP 
      make DESTDIR=$SNAPCRAFT_PART_INSTALL install
    build-packages:
      - build-essential
      - dos2unix
      - libboost-all-dev
      - texinfo
      - texi2html
      - libxml2-dev
      - subversion
      - bison
      - flex
      - zlib1g-dev
      - m4
    stage-packages:
      - libicu60
      - libxml2
      - m4

apps:
  zcc:
    command: zcc
    environment:
      ZCCCFG: "$SNAP/share/z88dk/lib/config"
    plugs: [home, removable-media]
  z88dk-z80asm:
    command: z88dk-z80asm
    plugs: [home, removable-media]
  z88dk-dis:
    command: z88dk-dis
    plugs: [home, removable-media]
  z88dk-ticks:
    command: z88dk-ticks
    plugs: [home, removable-media]
  z88dk-zx7:
    command: z88dk-zx7
    plugs: [home, removable-media]
  z88dk-dzx7:
    command: z88dk-dzx7
    plugs: [home, removable-media]
  z88dk-lib:
    command: z88dk-lib
    plugs: [home, removable-media]
  z88dk-z80nm:
    command: z88dk-z80nm
    plugs: [home, removable-media]
  z88dk-zobjcopy:
    command: bin/z88dk-zobjcopy
    plugs: [home, removable-media]
  z88dk-basck:
    command: bin/z88dk-basck
    plugs: [home, removable-media]
  z88dk-z80svg:
    command: bin/z88dk-z80svg
    plugs: [home, removable-media]
  z88dk-font2pv1000:
    command: bin/z88dk-font2pv1000
    plugs: [home, removable-media]


